// smoke/templates/solid-app/src/App.tsx
import {
  RoomfulProvider,
  useAwareness,
  useConnectionStatus,
  usePresence,
  useRoom,
  useSharedState,
} from '@roomful/solid';
import type { JSX } from 'solid-js';

type SmokePresence = {
  color: string;
  name: string;
};

function SmokePanel(): JSX.Element {
  const room = useRoom<SmokePresence>();
  const presence = usePresence<SmokePresence>();
  const awareness = useAwareness();
  const status = useConnectionStatus();
  const [sharedState] = useSharedState('solid-smoke-state', {
    initialValue: { count: 1 },
    strategy: 'lww',
  });

  return (
    <pre>
      {JSON.stringify(
        {
          awareness: awareness.others().length,
          canConnect: typeof room.connect === 'function',
          count: sharedState().count,
          peers: presence.all().length,
          status: status(),
        },
        null,
        2,
      )}
    </pre>
  );
}

export function App(): JSX.Element {
  return (
    <RoomfulProvider
      presence={{ color: '#0891b2', name: 'Solid Smoke' }}
      roomId="publish-smoke-solid"
    >
      <SmokePanel />
    </RoomfulProvider>
  );
}

// smoke/templates/react-app/src/App.tsx
import {
  RoomfulProvider,
  useAwareness,
  useConnectionStatus,
  usePresence,
  useRoom,
  useSharedState,
} from '@roomful/react';
import type { ReactElement } from 'react';

type SmokePresence = {
  color: string;
  name: string;
};

function SmokePanel(): ReactElement {
  const room = useRoom<SmokePresence>();
  const presence = usePresence<SmokePresence>();
  const awareness = useAwareness();
  const status = useConnectionStatus();
  const [sharedState] = useSharedState('react-smoke-state', {
    initialValue: { count: 1 },
    strategy: 'lww',
  });

  return (
    <pre>
      {JSON.stringify(
        {
          awareness: awareness.others.length,
          canConnect: typeof room.connect === 'function',
          count: sharedState.count,
          peers: presence.all.length,
          status,
        },
        null,
        2,
      )}
    </pre>
  );
}

export function App(): ReactElement {
  return (
    <RoomfulProvider
      presence={{ color: '#4f46e5', name: 'React Smoke' }}
      roomId="publish-smoke-react"
    >
      <SmokePanel />
    </RoomfulProvider>
  );
}
